/**
 * Free-only fixtures (ENG-13). Each entry names a tracked `test/fixtures/**`
 * file or directory glob and the free consumers that read it. A mapped
 * fixture is exempt from the PR paid lane's unknown-dependency fallback; an
 * unmapped fixture that no paid touchfile registers restores the full gate.
 *
 * Every tracked fixture must be either registered by a paid touchfile
 * (test/helpers/touchfiles-data.ts) or listed here; test/free-fixtures.test.ts
 * enforces that inventory and that every consumer is free (not a paid test
 * file, not a registered paid dependency) and names the fixture.
 *
 * An empty consumer list marks a fixture nothing reads (a deletion candidate).
 * When a paid case starts reading a fixture, move it into that case's
 * touchfiles instead of keeping it here.
 */
export const FREE_FIXTURES: Readonly<Record<string, readonly string[]>> = {
  'test/fixtures/auq-matrix/**': ['test/auq-native-capture.test.ts'],
  'test/fixtures/autoplan-edit-digests-al.json': ['test/autoplan-edit-digests-al.test.ts'],
  'test/fixtures/autoplan-home-phase-entry-fb10.json': ['test/autoplan-method-read-audit.test.ts'],
  'test/fixtures/autoplan-owned-state-edit.json': ['test/autoplan-owned-state.test.ts'],
  'test/fixtures/autoplan-phase-consumption-491.json': ['test/autoplan-publication-guard.test.ts'],
  'test/fixtures/autoplan-phase-dash-ao.json': ['test/autoplan-phase-observer.test.ts'],
  'test/fixtures/autoplan-phase-entry-alias-f359.json': ['test/autoplan-method-read-audit.test.ts'],
  'test/fixtures/autoplan-phase-entry-cf74.json': ['test/autoplan-method-read-audit.test.ts'],
  'test/fixtures/autoplan-publication-boundary-361c.json': ['test/autoplan-publication-guard.test.ts'],
  'test/fixtures/autoplan-routing-manual-skills-ac.json': ['test/autoplan-pending-question.test.ts'],
  'test/fixtures/autoplan-settings-overwrite.json': ['test/helpers/claude-pty-runner.screen.unit.test.ts', 'test/plan-skill-questions.test.ts'],
  'test/fixtures/autoplan-setup-packet-o-call.json': ['test/plan-pending-question-pty.test.ts'],
  'test/fixtures/autoplan-setup-packet-o-screen.txt': ['test/plan-pending-question-pty.test.ts'],
  'test/fixtures/autoplan-with-result-au.json': ['test/autoplan-phase-observer.test.ts'],
  'test/fixtures/browse-judge/**': ['test/workflow-judge-cache.test.ts'],
  'test/fixtures/ceo-completion-handoff-m-call.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/ceo-completion-handoff-o-call.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/ceo-completion-handoff-q-call.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/ceo-count-ad-v2.json': ['test/ceo-count-ad-v2.test.ts'],
  'test/fixtures/ceo-count-s-distinct.json': ['test/plan-count-empty-review.test.ts'],
  'test/fixtures/ceo-existing-payment/**': ['test/ceo-finding-fixture.test.ts'],
  'test/fixtures/ceo-expansion-plural-36903600510.json': ['test/ceo-mode-option.test.ts'],
  'test/fixtures/ceo-handoff-n-calls.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/ceo-handoff-y-call.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/ceo-hold-note-briefs-36597762183.json': ['test/ceo-mode-option.test.ts'],
  'test/fixtures/ceo-mode-bundled-tab-local.json': ['test/ceo-mode-option.test.ts'],
  'test/fixtures/ceo-mode-clipped-mode-question-local.json': ['test/ceo-mode-option.test.ts'],
  'test/fixtures/ceo-mode-clipped-review-local.json': ['test/ceo-mode-option.test.ts'],
  'test/fixtures/ceo-mode-scrolled-review-36606688266.json': ['test/ceo-mode-option.test.ts'],
  'test/fixtures/ceo-paired-option-values.json': ['test/plan-review-decisions.test.ts'],
  'test/fixtures/ceo-section-loading-36597762183-report.md': ['test/ceo-section-loading-fixture.test.ts'],
  'test/fixtures/ceo-split-collection-3638.json': ['test/ceo-split-collection.test.ts'],
  'test/fixtures/ceo-stale-fill-decision/**': ['test/ceo-stale-fill-decision.test.ts'],
  'test/fixtures/ci-gate/**': ['test/gstack-ci-gate.test.ts'],
  'test/fixtures/claude-native-journal-roots-2.1.284.json': ['test/autoplan-publication-hook.test.ts', 'test/plan-count-transcript.test.ts'],
  'test/fixtures/codex-boundary-commands.json': ['test/codex-boundary-evidence.test.ts'],
  'test/fixtures/codex-review-sandbox-unavailable-37158847998.json': ['test/outside-voice-evidence.test.ts'],
  'test/fixtures/codex-review/**': ['test/codex-hardening.test.ts', 'test/outside-voice-evidence.test.ts', 'test/skill-validation.test.ts'],
  'test/fixtures/codex-sandbox/**': ['test/codex-eval-recording.test.ts', 'test/codex-model-probe.test.ts', 'test/outside-review-result.test.ts', 'test/outside-voice-invocation.test.ts'],
  'test/fixtures/context-bill/**': ['test/context-bill.test.ts', 'test/context-budget-ratchet.test.ts'],
  'test/fixtures/context-budget.json': ['test/helpers/capture-context-budget.ts', 'test/test-value-bar.test.ts'],
  'test/fixtures/coverage-audit-parallel-column.json': ['test/coverage-audit-evidence.test.ts'],
  'test/fixtures/coverage-audit-summary.json': ['test/coverage-audit-evidence.test.ts'],
  'test/fixtures/cso-eval/**': ['scripts/cso-eval.ts', 'test/cso-eval.test.ts', 'test/cso-stack-cold-integration.test.ts', 'test/helpers/cso-eval-oracles.ts'],
  'test/fixtures/cso-http-smoke.c': ['test/cso-docker-integration.test.ts'],
  'test/fixtures/cso-sarif/**': ['test/cso-scanner-cli.test.ts', 'test/cso-scanners.test.ts'],
  'test/fixtures/design-completion-envelope-90f.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/design-consultation-section-design-md.md': ['test/carve-section-sharding.test.ts'],
  'test/fixtures/design-count-native-8525.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/design-count-native-issue-fields.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/design-detector-source-public.json': ['test/design-detector-source-fixture.test.ts'],
  'test/fixtures/design-floor-focus-36597762183.json': ['test/helpers/claude-pty-runner.boundaries.unit.test.ts'],
  'test/fixtures/design-handoff-n-calls.json': ['test/design-completion-handoff-scored.test.ts'],
  'test/fixtures/design-handoff-q-calls.json': ['test/design-completion-handoff-scored.test.ts'],
  'test/fixtures/design-md-legacy.md': ['test/design-md.test.ts'],
  'test/fixtures/design-ui-focus-capture.json': ['test/plan-design-with-ui-fixture.test.ts'],
  'test/fixtures/devex-checkpoint-todos.json': ['test/plan-review-cases.test.ts'],
  'test/fixtures/devex-handoff-n-call.json': ['test/plan-count-dx-handoff.test.ts'],
  'test/fixtures/devex-handoff-o-call.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/devex-handoff-v-call.json': ['test/plan-count-dx-handoff.test.ts'],
  'test/fixtures/devex-handoff-z-call.json': ['test/plan-count-dx-handoff.test.ts'],
  'test/fixtures/devex-narrative-confirmation-36641820398.json': ['test/plan-floor-review.test.ts'],
  'test/fixtures/devex-narrative-confirmation-36794871032.json': ['test/plan-floor-review.test.ts'],
  'test/fixtures/devex-review-l-calls.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/disabled-plan-attribution-36597762183.json': ['test/disabled-plan-review-evidence.test.ts'],
  'test/fixtures/disabled-plan-attribution-local-rerun.json': ['test/disabled-plan-review-evidence.test.ts'],
  'test/fixtures/disabled-plan-self-report.json': ['test/disabled-plan-review-evidence.test.ts'],
  'test/fixtures/disabled-prior-clock-36903600510.json': ['test/disabled-dated-record-at.test.ts'],
  'test/fixtures/docsync-followup-echo-37188668421.json': ['test/docsync-child-marker.test.ts'],
  'test/fixtures/docsync-observer-commands.json': ['test/docsync-lifecycle-interface.test.ts'],
  'test/fixtures/dx-manual-handoff-ao.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/dx-prerequisite-r-call.json': ['test/plan-count-prerequisite.test.ts'],
  'test/fixtures/dx-selected-navigation-ap.json': ['test/dx-selected-navigation-ap.test.ts'],
  'test/fixtures/eng-annotated-cache-au.json': ['test/eng-first-review.test.ts'],
  'test/fixtures/eng-architecture-cache-av-calls.json': ['test/eng-first-review.test.ts'],
  'test/fixtures/eng-batching-bullet-target-rerun.json': ['test/eng-seeded-coverage.test.ts'],
  'test/fixtures/eng-batching-report-title-36798539821.json': ['test/eng-seeded-coverage.test.ts'],
  'test/fixtures/eng-batching-section-heading-37158847998.json': ['test/eng-batching-saved-ledger.test.ts'],
  'test/fixtures/eng-batching-unsourced-brief-36606688266.json': ['test/eng-seeded-coverage.test.ts'],
  'test/fixtures/eng-cache-brief-am.json': ['test/eng-first-review.test.ts'],
  'test/fixtures/eng-cache-owner-an.json': ['test/eng-first-review.test.ts'],
  'test/fixtures/eng-completed-navigation-cab3.json': ['test/eng-published-navigation.test.ts'],
  'test/fixtures/eng-fb10-count-public.json': ['test/eng-semantic-terminal.test.ts'],
  'test/fixtures/eng-next-handoff-ah.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/eng-published-navigation.json': ['test/eng-published-navigation.test.ts'],
  'test/fixtures/eng-task-pause-navigation-f359.json': ['test/plan-count-completion.test.ts'],
  'test/fixtures/eng-test-plan-edit-cli.js': ['test/eng-test-plan-edit-approval.test.ts'],
  'test/fixtures/eng-test-plan-edit-dacc.json': ['test/eng-test-plan-edit-approval.test.ts'],
  'test/fixtures/exit-propagation/**': ['test/exit-propagation.test.ts'],
  'test/fixtures/free-shard-capture.ts': ['test/test-free-shards-capture.test.ts'],
  'test/fixtures/golden/**': ['test/host-config.test.ts', 'test/ship-review-loop.test.ts'],
  'test/fixtures/impeccable-antipatterns.json': ['test/design-catalog.test.ts', 'test/impeccable-fixtures.test.ts'],
  'test/fixtures/impeccable-captures.meta.json': ['test/design-detect-contract.test.ts', 'test/impeccable-fixtures.test.ts'],
  'test/fixtures/impeccable-detect-dom-sample.json': ['test/impeccable-fixtures.test.ts'],
  'test/fixtures/impeccable-detect-help.txt': ['test/impeccable-fixtures.test.ts'],
  'test/fixtures/judge-calibration/**': ['scripts/judge-calibration.ts', 'test/judge-calibration.test.ts'],
  'test/fixtures/module-size-ratchet.json': ['test/helpers/module-size.ts', 'test/module-size-ratchet.test.ts'],
  'test/fixtures/module-size/**': ['test/helpers/module-size.ts', 'test/module-size-ratchet.test.ts'],
  'test/fixtures/native-auq-boxed-full-body-sep21.json': ['test/auq-native-capture.test.ts'],
  'test/fixtures/native-auq-clipped-elided-sep21.json': ['test/auq-native-capture.test.ts'],
  'test/fixtures/native-auq-devex-clipped-elided-sep21.json': ['test/auq-native-capture.test.ts'],
  'test/fixtures/native-auq-margin-elided-sep21.json': ['test/auq-native-capture.test.ts'],
  'test/fixtures/native-auq-packet-clipped-elided-sep21.json': ['test/auq-native-capture.test.ts'],
  'test/fixtures/outside-voice-failure-prose-allowlist.json': ['test/outside-voice-failure-policy.test.ts'],
  'test/fixtures/paid-report-census/**': ['test/paid-report-census.test.ts', 'test/paid-shards.test.ts'],
  'test/fixtures/parity-baseline-v1.44.1.json': ['test/helpers/capture-parity-baseline.test.ts', 'test/parity-baseline-integrity.test.ts'],
  'test/fixtures/parity-baseline-v1.64.1.0.json': ['test/parity-suite.test.ts', 'test/qa-lazy-sections.test.ts', 'test/skill-size-budget.test.ts'],
  'test/fixtures/parity-baseline-v1.81.0.0.json': ['test/skill-size-budget.test.ts'],
  'test/fixtures/plan-count-design-questionless-report.md': ['test/plan-count-empty-review.test.ts'],
  'test/fixtures/plan-create-cropped-title-batching.json': ['test/plan-create-combined-permission.test.ts'],
  'test/fixtures/plan-format-kind-notes.json': ['test/plan-format-kind-note.test.ts'],
  'test/fixtures/plans/autoplan-dashboard.md': ['test/autoplan-init.test.ts', 'test/autoplan-preconfigured-onboarding-ar.test.ts', 'test/autoplan-snapshot.test.ts'],
  'test/fixtures/plans/autoplan-focus-appearance-design.md': [],
  'test/fixtures/plans/autoplan-focus-appearance.md': [],
  'test/fixtures/plans/ui-heavy-feature-design.md': [],
  'test/fixtures/pty-idle-turn-end.json': ['test/helpers/claude-pty-runner.runners.unit.test.ts', 'test/helpers/claude-pty-runner.screen.unit.test.ts'],
  'test/fixtures/redact-diagram/**': ['test/redact-context-exemptions.test.ts'],
  'test/fixtures/remote-identity-vectors.json': ['test/bin-context-windows-slug.test.ts', 'test/gstack-slug-parity.test.ts', 'test/remote-identity-vectors.test.ts'],
  'test/fixtures/review-design-lite-reports-ci-36633323521.json': ['test/review-finalization-budget.test.ts'],
  'test/fixtures/shard-cli-parity/**': ['test/shard-cli-parity.test.ts'],
  'test/fixtures/shard-equivalence/**': ['test/shard-engine-equivalence.test.ts'],
  'test/fixtures/shared-libs-no-change-ci-public.json': ['test/shared-libs-fixture.test.ts'],
  'test/fixtures/shared-libs-plan-callers-fixes-behavior-local.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs-plan-callers-future-risk-37195203538.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs-plan-callers-no-hardening-36633323521.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs-plan-callers-out-of-scope-37151477069.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs-plan-callers-parity-36776104571.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs-plan-callers-passing-censuses.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs-plan-callers-slash-scope-37174266054.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs-plan-callers-verbless-scope-37186854666.json': ['test/shared-libs-plan-actor.test.ts'],
  'test/fixtures/shared-libs/**': ['test/shared-libs-checker-interface-evidence.test.ts', 'test/shared-libs-fixture.test.ts', 'test/shared-libs-plan-actor.test.ts', 'test/shared-libs-revalidation-prompt.test.ts', 'test/shared-libs-review-start-evidence.test.ts', 'test/shared-libs-source-reads.test.ts', 'test/shared-libs-stage-actor.test.ts'],
  'test/fixtures/ship-triage/**': ['test/ship-triage-labels.test.ts'],
  'test/fixtures/skillify-narration/**': ['test/skill-fixture.test.ts'],
  'test/fixtures/test-value-seam-evidence.json': ['test/test-value-bar.test.ts'],
  'test/fixtures/third-party-actions-recovery-public.json': ['test/third-party-actions-recording.test.ts', 'test/third-party-actions.test.ts'],
  'test/fixtures/touchfile-moved-code/**': ['test/touchfiles.test.ts'],
};
