name: OSV Scanner

on:
  schedule:
    - cron: '23 7 * * 1'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: osv-scanner
  cancel-in-progress: true

jobs:
  scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@f4cfcc01edc9c8b756a9b873b7a623ca674da51e # v2.3.8
    with:
      scan-args: |-
        --config=.osv-scanner.toml
        --include-git-root
        --recursive
        ./
